apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: exporters.monitoring.operator.ibm.com
spec:
  group: monitoring.operator.ibm.com
  names:
    kind: Exporter
    listKind: ExporterList
    plural: exporters
    singular: exporter
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Exporter is the Schema for the exporters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ExporterSpec defines the desired state of Exporter
          properties:
            certs:
              description: Certs defines certifications used by all exporters
              properties:
                caSecret:
                  description: All certificates for monitoring stack should be signed
                    by this CA
                  type: string
                exporterSecret:
                  description: Exorters' tls cert. Define the secret name. It will
                    not be recreated when existing It can be created by either this
                    operator or prometheus operator. Make sure secret name defined
                    by both operator same
                  type: string
                issuer:
                  description: The clusterissuer name. It is used when provider is
                    certmanager
                  type: string
              required:
              - caSecret
              - exporterSecret
              type: object
            collectd:
              description: Collectd defines desired state of Collectd exporter
              properties:
                collectorPort:
                  format: int32
                  type: integer
                enable:
                  type: boolean
                image:
                  type: string
                metricsPort:
                  format: int32
                  type: integer
                resource:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                routerResource:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                serviceAccount:
                  description: SCC privileged should have been added to the service
                    account already by administrator
                  type: string
              required:
              - enable
              type: object
            imagePolicy:
              description: PullPolicy describes a policy for if/when to pull a container
                image
              type: string
            imagePullSecrets:
              items:
                type: string
              type: array
            kubeStateMetrics:
              description: KubeStateMetrics defines desired state of kube-state-metrics
              properties:
                enable:
                  type: boolean
                image:
                  type: string
                port:
                  format: int32
                  type: integer
                resource:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                routerResource:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                serviceAccount:
                  description: SCC privileged should have been added to the service
                    account already by administrator
                  type: string
              required:
              - enable
              type: object
            nodeExporter:
              description: NodeExporter defines desired state of NodeExporter exporter
              properties:
                enable:
                  type: boolean
                healtyPort:
                  format: int32
                  type: integer
                hostPort:
                  format: int32
                  type: integer
                image:
                  type: string
                resource:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                routerResource:
                  description: ResourceRequirements describes the compute resource
                    requirements.
                  properties:
                    limits:
                      additionalProperties:
                        type: string
                      description: 'Limits describes the maximum amount of compute
                        resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                    requests:
                      additionalProperties:
                        type: string
                      description: 'Requests describes the minimum amount of compute
                        resources required. If Requests is omitted for a container,
                        it defaults to Limits if that is explicitly specified, otherwise
                        to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/'
                      type: object
                  type: object
                serviceAccount:
                  description: //SCC privileged should have been added to the service
                    account already by administrator
                  type: string
                servicePort:
                  format: int32
                  type: integer
              required:
              - enable
              type: object
            routerImage:
              type: string
          type: object
        status:
          description: ExporterStatus defines the observed state of Exporter
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
