apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: exporter
    app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
  name: ibm-monitoring-exporters-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-exporters-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: exporter
        app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
        name: ibm-monitoring-exporters-operator
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.3.0"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-exporters-operator
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: ibm-monitoring-exporters-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-monitoring-exporters-operator:1.8.0
          command:
          - ibm-monitoring-exporters-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-exporters-operator"
            - name: ROUTER_IMAGE
              value: icp-management-ingress@sha256:c49e551f9f68f2e024a8a50e35f2ce4a6ec86f169d9bfb489b47fa6e8e216571
            - name: COLLECTD_IMAGE
              value: collectd-exporter@sha256:b72a2808d385d53ad3a292076fd6337d05ef81c4f4158aae39bf72d11830b056
            - name: NODE_IMAGE
              value: node-exporter@sha256:a8cf0c4af2a6a07ddedf5cc3b2aec002c037d20678e73e272b87d36a73bf8b8b
            - name: KUBESTATE_IMAGE
              value: kube-state-metrics@sha256:aaf26bac7dcfb3dae0e1355ad29b30b7613b14f3fbba4b4229ac3492186751d5
