kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-monitoring-exporters-operator
subjects:
- kind: ServiceAccount
  name: ibm-monitoring-exporters-operator
  namespace: ibm-common-services
roleRef:
  kind: ClusterRole
  name: ibm-monitoring-exporters-operator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-monitoring-exporter
subjects:
- kind: ServiceAccount
  name: ibm-monitoring-exporter
roleRef:
  kind: Role
  name: ibm-monitoring-exporter
  apiGroup: rbac.authorization.k8s.io
