apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "monitoring.operator.ibm.com/v1alpha1",
          "kind": "Exporter",
          "metadata": {
            "name": "ibm-monitoring"
          },
          "spec": {
            "certs": {
              "exporterSecret": "ibm-monitoring-exporter-certs",
              "issuer": "cs-ca-clusterissuer",
              "monitoringClientSecret": "ibm-monitoring-client-certs",
              "autoClean": true
            },
            "collectd": {
              "collectorPort": 25826,
              "enable": true,
              "image": "quay.io/opencloudio/collectd-exporter:v0.4.0-build.4",
              "metricsPort": 8443,
              "resource": {},
              "routerResource": {
                "limits": {
                  "cpu": "200m",
                  "memory": "256Mi"
                },
                "requests": {
                  "cpu": "10m",
                  "memory": "64Mi"
                }
              }
            },
            "imagePullSecrets": [
              "infra-registry-key"
            ],
            "kubeStateMetrics": {
              "enable": true,
              "image": "quay.io/opencloudio/kube-state-metrics:v1.9.4-build.2",
              "port": 8443
            },
            "nodeExporter": {
              "enable": true,
              "healtyPort": 8556,
              "hostPort": 9109,
              "image": "quay.io/opencloudio/node-exporter:v0.18.1-build.2",
              "servicePort": 8555
            },
            "routerImage": "quay.io/opencloudio/icp-management-ingress:2.5.1"
          }
        }
      ]
    capabilities: Basic Install
    categories: Monitoring
    certified: 'false'
    createdAt: 2020-03-25 12:00:00
    support: IBM
    description: Provisions node-exporter, kube-state-metrics and collectd exporter with tls enabled
    repository: https://github.com/IBM/ibm-monitoring-exporters-operator
  name: ibm-monitoring-exporters-operator.v1.8.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Exporter defines information for collectd exporter, node-exporter and kube-state-matrics
      kind: Exporter
      name: exporters.monitoring.operator.ibm.com
      version: v1alpha1
      displayName: IBM Monitoring Exporter
  description: IBM Monitoring Exporters Operator provisions node-exporter, kube-state-metrics and collectd exporter with tls enabled
  displayName: IBM Monitoring Exporters Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - '*'
          verbs:
          - list
        - apiGroups:
          - apps
          resources:
          - '*'
          verbs:
          - list
        - apiGroups:
          - batch
          resources:
          - '*'
          verbs:
          - list
        - apiGroups:
          - extensions
          resources:
          - '*'
          verbs:
          - list
        - apiGroups:
          - networking.k8s.io
          resources:
          - '*'
          verbs:
          - list
        - apiGroups:
          - storage.k8s.io
          resources:
          - '*'
          verbs:
          - list
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: ibm-monitoring-exporter
      - rules:
        - apiGroups:
          - ""
          resources:
          - services
          - configmaps
          - pods
          - secrets
          - endpoints
          - events
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - monitoring.operator.ibm.com
          resources:
          - exporters
          - exporters/finalizers
          verbs:
          - '*'
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - certificates
          verbs:
          - '*'
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - clusterissuers
          verbs:
          - use
        serviceAccountName: ibm-monitoring-exporters-operator
      deployments:
      - name: ibm-monitoring-exporters-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-monitoring-exporters-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-monitoring-exporters-operator
              annotations:
                productName: IBM Cloud Platform Common Services
                productID: "068a62892a1e4db39641342e592daa25"
                productVersion: "3.3.0"
                productMetric: FREE
            spec:
              containers:
              - command:
                - ibm-monitoring-exporters-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-monitoring-exporters-operator
                image: quay.io/opencloudio/ibm-monitoring-exporters-operator
                imagePullPolicy: Always
                name: ibm-monitoring-exporters-operator
                resources: {}
              serviceAccountName: ibm-monitoring-exporters-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  maturity: alpha
  provider: 
    name: IBM
  replaces: ibm-monitoring-exporters-operator.v0.0.0
  version: 1.8.0
