apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "monitoring.operator.ibm.com/v1alpha1",
          "kind": "Exporter",
          "metadata": {
            "name": "ibm-monitoring"
          },
          "spec": {
            "certs": {
              "caSecret": "cluster-ca-cert",
              "exporterSecret": "ibm-monitoring-exporter-certs",
              "issuer": "icp-ca-issuer",
              "monitoringClientSecret": "ibm-monitoring-client-certs"
            },
            "collectd": {
              "collectorPort": 25826,
              "enable": true,
              "image": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/collectd-exporter:v0.4.0-build.3",
              "metricsPort": 8443,
              "resource": {},
              "routerResource": {
                "limits": {
                  "cpu": "200m",
                  "memory": "256Mi"
                },
                "requests": {
                  "cpu": "10m",
                  "memory": "64Mi"
                }
              }
            },
            "imagePullSecrets": [
              "infra-registry-key"
            ],
            "kubeStateMetrics": {
              "enable": true,
              "image": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/kube-state-metrics:v1.9.4-build.1",
              "port": 8443
            },
            "nodeExporter": {
              "enable": true,
              "healtyPort": 8556,
              "hostPort": 9109,
              "image": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/node-exporter:v0.18.1-build.1",
              "servicePort": 8555
            },
            "routerImage": "hyc-cloud-private-edge-docker-local.artifactory.swg-devops.com/ibmcom-amd64/icp-management-ingress:2.5.0"
          }
        }
      ]
    capabilities: Basic Install
  name: ibm-monitoring-exporters-operator.v0.0.1
  namespace: ibm-common-services
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Exporter defines information for collectd exporter, node-exporter and kube-state-matrics
      kind: Exporter
      name: exporters.monitoring.operator.ibm.com
      version: v1alpha1
      displayName: IBM Monitoring Exporter
    required:
    - description: Certificate is a type to represent a Certificate from ACME
      kind: Certificate
      name: certmanager.k8s.io
      version: v1alpha1
      displayName: Cert Manager Certificate
  description: IBM Monitoring Exporters Operator provisions node-exporter, kube-state-metrics and collectd exporter with tls enabled
  displayName: IBM Monitoring Exporters Operator
  install:
    spec:
      deployments:
      - name: ibm-monitoring-exporters-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: ibm-monitoring-exporters-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: ibm-monitoring-exporters-operator
            spec:
              containers:
              - command:
                - ibm-monitoring-exporters-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: ibm-monitoring-exporters-operator
                image: quay.io/opencloudio/ibm-monitoring-exporters-operator-amd64:09759280
                imagePullPolicy: Always
                name: ibm-monitoring-exporters-operator
                resources: {}
              serviceAccountName: ibm-monitoring-exporters-operator
      permissions:
      - rules:
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          resources:
          - securitycontextconstraints
          verbs:
          - use
        serviceAccountName: ibm-monitoring-exporter
      - rules:
        - apiGroups:
          - ""
          resources:
          - services
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - monitoring.operator.ibm.com
          resources:
          - exporters
          - exporters/finalizers
          verbs:
          - '*'
        - apiGroups:
          - certmanager.k8s.io
          resources:
          - certificates
          - issuers
          verbs:
          - '*'
        serviceAccountName: ibm-monitoring-exporters-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: ibm-monitoring-exporters-operator.v0.0.0
  version: 0.0.1
